name: Secure
on: workflow_call
permissions: {}
jobs:
  secrets:
    runs-on: ubuntu-24.04-arm
    steps:
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      with:
        persist-credentials: false
    - uses: ./.github/actions/setup-nix
    - name: Scan secrets
      run: nix develop .#scanSecrets -c trufflehog git file://. --branch "${SHA}" --fail --github-actions --results=verified,unknown
      env:
        SHA: ${{ github.sha }}
